USE [SRM-LENGUAJESIII]

SELECT * FROM MEDICOS
SELECT * FROM ESPECIALIDADES
SELECT * FROM EMPLEADOS
SELECT * FROM HORARIOS
SELECT * FROM RESERVAS
SELECT * FROM HORARIOS_HORA

DELETE FROM RESERVAS
DELETE FROM PACIENTES
DELETE FROM HORARIOS_HORA
DELETE FROM HORARIOS
DELETE FROM MEDICOS
DELETE FROM EMPLEADOS

DBCC CHECKIDENT ('RESERVAS', RESEED, 0)
DBCC CHECKIDENT ('PACIENTES', RESEED, 0)
DBCC CHECKIDENT ('HORARIOS_HORA', RESEED, 0)
DBCC CHECKIDENT ('HORARIOS', RESEED, 0)
DBCC CHECKIDENT ('MEDICOS', RESEED, 0)
DBCC CHECKIDENT ('EMPLEADOS', RESEED, 0)